openapi: 3.0.0
info:
  title: Cruise Control API
  description: Cruise-control is the first of its kind to fully automate the dynamic workload rebalance and self-healing of a kafka cluster. It provides great value to Kafka users by simplifying the operation of Kafka clusters.
  version: 1.0.0
servers:
  - url: /{urlPrefix}
    variables:
      urlPrefix:
        default: kafkacruisecontrol
        description: REST API default url prefix, configured by webserver.api.urlprefix
paths:
  /add_broker:
    $ref: 'endpoints/addBroker.yaml#/AddBrokerEndpoint'
  /admin:
    $ref: 'endpoints/admin.yaml#/AdminEndpoint'
  /bootstrap:
    $ref: 'endpoints/bootstrap.yaml#/BootstrapEndpoint'
  /demote_broker:
    $ref: 'endpoints/demoteBroker.yaml#/DemoteBrokerEndpoint'
  /fix_offline_replicas:
    $ref: 'endpoints/fixOfflineReplicas.yaml#/FixOfflineReplicasEndpoint'
  /kafka_cluster_state:
    $ref: 'endpoints/kafkaClusterState.yaml#/KafkaClusterStateEndpoint'
  /load:
    $ref: 'endpoints/load.yaml#/LoadEndpoint'
  /partition_load:
    $ref: 'endpoints/partitionLoad.yaml#/PartitionLoadEndpoint'
  /pause_sampling:
    $ref: 'endpoints/pauseSampling.yaml#/PauseSamplingEndpoint'
  /proposals:
    $ref: 'endpoints/proposals.yaml#/ProposalsEndpoint'
  /rebalance:
    $ref: 'endpoints/rebalance.yaml#/RebalanceEndpoint'
  /remove_broker:
    $ref: 'endpoints/removeBroker.yaml#/RemoveBrokerEndpoint'
  /rightsize:
    $ref: 'endpoints/rightsize.yaml#/RightsizeEndpoint'
  /resume_sampling:
    $ref: 'endpoints/resumeSampling.yaml#/ResumeSamplingEndpoint'
  /review:
    $ref: 'endpoints/review.yaml#/ReviewEndpoint'
  /review_board:
    $ref: 'endpoints/reviewBoard.yaml#/ReviewBoardEndpoint'
  /state:
    $ref: 'endpoints/state.yaml#/StateEndpoint'
  /stop_proposal_execution:
    $ref: 'endpoints/stopProposalExecution.yaml#/StopProposalExecutionEndpoint'
  /topic_configuration:
    $ref: 'endpoints/topicConfiguration.yaml#/TopicConfigurationEndpoint'
  /train:
    $ref: 'endpoints/train.yaml#/TrainEndpoint'
  /user_tasks:
    $ref: 'endpoints/userTasks.yaml#/UserTasksEndpoint'
  /remove_disks:
    $ref: 'endpoints/removeDisks.yaml#/RemoveDisksEndpoint'
