version: '3.2'

services:
  alpine:
    image: alpine
    user: ${USER_ID}:${GROUP_ID}
    userns_mode: host
    working_dir: /app
    volumes:
    - .:/app
        
  k14s:
    image: k14s/image:kbld-rand-1591920752754379000-1908418319647
    user: ${USER_ID}:${GROUP_ID}
    userns_mode: host
    working_dir: /app/.buildkite
    volumes:
    - ..:/app