#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("funcs.star", "utils" )
---

#@ mainline_build = data.values.branch == "main"
#@ changes = json.decode(data.values.changed_folders)
#@ triggers = data.values.build_triggers
#@ build_type = utils.get_build_type(changes, triggers)

env:
  ARTIFACTORY_REGION: prod

steps: 

#@ if build_type == "ignore":
  - label: "Nothing of consequence has changed, so doing nothing"
    commands:
      - echo "done"

#@ else:

  #@ if build_type == "helm" or build_type == "both":
    #@ if/end mainline_build:
  - label: Building and publishing Helm chart
    #@ if/end not mainline_build:
  - label: Building Helm chart
    env:
      HELM_VERSION: ${BUILDKITE_BUILD_NUMBER}
    commands:
      - make lint
    #@ if/end mainline_build:
      - make helm
    agents:
      queue: build.linux
  #@ end

  #@ if build_type == "code" or build_type == "both":
    #@ if/end mainline_build:
  - label: Building and publishing Cruise-Control container
    #@ if/end not mainline_build:
  - label: Building Cruise-Control container
    env:
      IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}
    commands:
      - make image
    #@ if/end mainline_build:
      - make available
    agents:
      queue: build.linux
  #@ end
#@ end