#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("funcs.star", "utils" )
---

#@ mainline_build = data.values.branch == "main"
#@ changes = json.decode(data.values.changed_folders)
#@ triggers = data.values.build_triggers
#@ build_type = utils.get_build_type(changes, triggers)

env:
  ARTIFACTORY_REGION: prod

steps: 

#@ if build_type == "ignore":
  - label: "Nothing of consequence has changed, so doing nothing"
    commands:
      - echo "done"
#@ else:
  #@ if build_type == "helm" or build_type == "both":
  - label: Building and publishing Helm chart
    commands:
      - make lint
      - make helm
    agents:
      queue: build.linux
  #@ end
  #@ if build_type == "code" or build_type == "both":
  - label: Building and publishing Cruise-Control container
    commands:
      - make image
      - make available
    agents:
      queue: build.linux
  #@ end
#@ end