openapi: 3.0.0
info:
  title: Cruise Control API
  description: Cruise-control is the first of its kind to fully automate the dynamic workload rebalance and self-healing of a kafka cluster. It provides great value to Kafka users by simplifying the operation of Kafka clusters.
  version: 1.0.0
paths:
  /kafkacruisecontrol/add_broker:
    $ref: 'endpoints/addBroker.yaml#/AddBrokerEndpoint'
  /kafkacruisecontrol/admin:
    $ref: 'endpoints/admin.yaml#/AdminEndpoint'
  /kafkacruisecontrol/bootstrap:
    $ref: 'endpoints/bootstrap.yaml#/BootstrapEndpoint'
  /kafkacruisecontrol/demote_broker:
    $ref: 'endpoints/demoteBroker.yaml#/DemoteBrokerEndpoint'
  /kafkacruisecontrol/fix_offline_replicas:
    $ref: 'endpoints/fixOfflineReplicas.yaml#/FixOfflineReplicasEndpoint'
  /kafkacruisecontrol/kafka_cluster_state:
    $ref: 'endpoints/kafkaClusterState.yaml#/KafkaClusterStateEndpoint'
  /kafkacruisecontrol/partition_load:
    $ref: 'endpoints/partitionLoad.yaml#/PartitionLoadEndpoint'
  /kafkacruisecontrol/pause_sampling:
    $ref: 'endpoints/pauseSampling.yaml#/PauseSamplingEndpoint'
  /kafkacruisecontrol/proposals:
    $ref: 'endpoints/proposals.yaml#/ProposalsEndpoint'
  /kafkacruisecontrol/rebalance:
    $ref: 'endpoints/rebalance.yaml#/RebalanceEndpoint'
  /kafkacruisecontrol/remove_broker:
    $ref: 'endpoints/removeBroker.yaml#/RemoveBrokerEndpoint'
  /kafkacruisecontrol/resume_sampling:
    $ref: 'endpoints/resumeSampling.yaml#/ResumeSamplingEndpoint'
  /kafkacruisecontrol/review:
    $ref: 'endpoints/review.yaml#/ReviewEndpoint'
  /kafkacruisecontrol/review_board:
    $ref: 'endpoints/reviewBoard.yaml#/ReviewBoardEndpoint'
  /kafkacruisecontrol/state:
    $ref: 'endpoints/state.yaml#/StateEndpoint'
  /kafkacruisecontrol/stop_proposal_execution:
    $ref: 'endpoints/stopProposalExecution.yaml#/StopProposalExecutionEndpoint'
  /kafkacruisecontrol/topic_configuration:
    $ref: 'endpoints/topicConfiguration.yaml#/TopicConfigurationEndpoint'
  /kafkacruisecontrol/train:
    $ref: 'endpoints/train.yaml#/TrainEndpoint'
  /kafkacruisecontrol/user_tasks:
    $ref: 'endpoints/userTasks.yaml#/UserTasksEndpoint'
