name: build-publish-docker-image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/docker/build-push-action
      - uses: docker/build-push-action@v1
        with:
          dockerfile: docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: adobe/cruise-control
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          add_git_labels: true
